["$globals"]
shell = "bash"
version = 4

[all]
phony = true
commands = [
    "yam -d jetbrains_settings/pycharm/ all",
    "yam -d jetbrains_settings/datagrip/ all",
    "yam -d jetbrains_settings/idea/ all",
]
