[commands.swipe.three]
up = "xdotool key ctrl+meta+Up"
down = "xdotool key ctrl+meta+Down"
left = "xdotool key ctrl+meta+Left"
right = "xdotool key ctrl+meta+Right"

[commands.swipe.four]
up = "xdotool key ctrl+F9"
down = "xdotool key ctrl+F10"
left = ""
right = ""
