alias eww=emacs
alias enw="emacs -nw"
alias ls="ls --color"
alias la="ls --color -A"
alias ll="ls --color -lG"
alias llh="ls --color -lGh"
alias lla="ls --color -lGA"
alias llah="ls --color -lGAh"
alias manage="python manage.py"
alias dj_server="python manage.py runserver_plus"
alias dj_shell="python manage.py shell_plus"
alias dj_celery="celery -A django_transmission worker -c 8 -l info"
alias grep="grep --color=auto"
