alias ls="ls --color"
alias la="ls --color -A"
alias ll="ls --color -l"
alias llh="ls --color -lh"
alias lla="ls --color -lA"
alias llah="ls --color -lAh"
alias manage="python manage.py"
alias grep="grep --color=auto"
alias tmux="tmux -2"
alias vi="nvim"
