(column-number-mode t)
(display-time-mode 1)
(electric-pair-mode t)
(auto-fill-mode -1)
(global-linum-mode 1)
(setq-default indent-tabs-mode nil)
(popwin-mode 1)
(delete-selection-mode 1)
(drag-stuff-global-mode 1)
(global-auto-complete-mode t)
(whole-line-or-region-global-mode t)
(xterm-mouse-mode t)
(xterm-mouse-mode t)
(editorconfig-mode 1)
