[all]
alias = "settings.zip"

["settings.zip"]
requires = [
    "settings"
]
commands = [
    "rm -f {.target}",
    "cd settings; zip -r ${.target} .",
]

[settings]
exists_only = true
recursive = true
